Update build.rs (#26)
Not sure but msvc doen't have -Werror flag
Anyway, I have some bug with compiling on Windows:

error: failed to run custom build command for `tblgen v0.6.0`
Caused by:
process didn't exit successfully:
`D:\spaceless\projs\rolang\target\debug\build\tblgen-a0e5f371761e9f4a\build-script-build`
(exit code: 1)
  --- stderr
error occurred in cc-rs: command did not execute successfully (status
code exit code: 2):
"D:\\_programs\\VS\\2022\\VC\\Tools\\MSVC\\14.44.35207\\bin\\HostX64\\x64\\cl.exe"
"-nologo" "-MD" "-Z7" "-Brepro" "-std:c++17" "-I" "cc/include" "-I"
"D:/_programs/msys64/clang64/include" "-Werror"
"-ID:/_programs/msys64/clang64/include" "-std=c++17" "-stdlib=libc++"
"-fno-exceptions" "-funwind-tables" "-D_FILE_OFFSET_BITS=64"
"-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS"
"-D__STDC_LIMIT_MACROS"
"-FoD:\\spaceless\\projs\\rolang\\target\\debug\\build\\tblgen-c2973b152bb99b4a\\out\\eaa0b8528c4d35fb-Record.o"
"-c" "cc/lib\\Record.cpp"

warning: tblgen@0.6.0: cl: ��������� ��ப� error D8021: �������⨬� �᫮���
��㬥�� "/Werror"

#edit:

even with this fix it for some reason gives more warnings:

warning: tblgen@0.6.0: cl: ��������� ��ப� warning D9002: �ய�� �������⭮��
��ࠬ��� "-std=c++17"
warning: tblgen@0.6.0: cl: ��������� ��ப� warning D9002: �ய�� �������⭮��
��ࠬ��� "-stdlib=libc++"
warning: tblgen@0.6.0: cl: ��������� ��ப� warning D9002: �ய�� �������⭮��
��ࠬ��� "-fno-exceptions"
warning: tblgen@0.6.0: cl: ��������� ��ப� warning D9002: �ய�� �������⭮��
��ࠬ��� "-funwind-tables"

Maybe, think about this pull request not about as pull request but as a
bug representation (cl takes unknown for it flags on Windows). I'm just
new to github and not sure how to do it normally and also do not
undarstand how `cc` works.

---------

Co-authored-by: VladEmirX <147193089+VladEmirX@users.noreply.github.com>
Co-authored-by: Yota Toyama <raviqqe@gmail.com>